version: '4.34'

services:
  db:
    image: mysql:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: senha_root
      MYSQL_DATABASE: banco
      MYSQL_USER: adminlocal
      MYSQL_PASSWORD: senhamysql

    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: